sudo: required
services:
  - docker


before_install:
  - docker build -t sgamusb/docker-react -f Dockerfile.dev .


script:
  - docker run sgamusb/docker-react npm run test -- --coverage

language: generic